# server
server:
  port: 6825

# spring
spring:
  application:
    name: service-sys
  profiles:
    active: @current.active.profile@
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  boot:
    admin:
      client:
        url: @spring.boot.admin.url@
        usernmae: @security.user.name@
        password: @security.user.pwd@
        instance:
          prefer-ip: true
  security:
    user:
      name: @security.user.name@
      password: @security.user.pwd@

# eureka
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: @eureka.url@

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.blue.eyes.entity.*.*
  global-config:
    db-config:
      db-type: mysql
      id-type: uuid
      field-strategy: not_null
      logic-delete-value: 1
      logic-not-delete-value: 0
      table-underline: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true

